### ISSUE TITLE
Compilation Issues

### ISSUE THREAD

**Issue by guoswang** [sunnyxiaohu/R-C3D.pytorch#1]
Hi,
Thanks your great works!  When I'm compliing the code by `sh make.sh`, there is coming the problems:

`gcc: error: /home/XXX/R-C3D.pytorch/lib/model/nms/src/nms_cuda.c: No such file or directory`

I think the reasons leading to problems maybe that the codes missed the 'nms_cuda.c'.  Can you help me?

Thanks a lot!

**Comment by sunnyxiaohu** [comment]
I have fixed the bug~
Thanks!
