### ISSUE TITLE
When perform action detection, do I need to pay attention to args.num_classes ?

### ISSUE THREAD

**Issue by yzheng97** [sunnyxiaohu/R-C3D.pytorch#10]
This parameter is set for action classification. It seems that the class num for detection task can be directly read from .pkl file. 

> args_num_classes = 201

**Comment by sunnyxiaohu** [comment]
Yes, detection task also needs the parameter setting (args.num_classes).

**Comment by yzheng97** [comment]
Thanks! I've successfully run your code.
