### ISSUE TITLE
A typo in trainval_net.py

### ISSUE THREAD

**Issue by shanshuo** [sunnyxiaohu/R-C3D.pytorch#12]
Hi, when I run R-C3D on THUMOS14. It seems that there is a typo in https://github.com/sunnyxiaohu/R-C3D.pytorch/blob/master/trainval_net.py#L328. I think this should be `args.gpus` instead of `arg.mGPUs`. Cause the following error occurs when running the code.

```
Traceback (most recent call last):
  File "trainval_net.py", line 330, in <module>
    if args.mGPUs:
AttributeError: 'Namespace' object has no attribute 'mGPUs'
```

**Comment by sunnyxiaohu** [comment]
Sorry for delaying your reply. Yes, you can use len(args.gpus)>1 instead. I have fix the typo and add multiple gpu training support. Thank you.
