### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by honest2017** [sunnyxiaohu/R-C3D.pytorch#14]
with open(os.path.join(meta_dir, 'detclasslist.txt'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/media/msi/文档/action-datasets/UCF-101/annotation_val/detclasslist.txt'
I want to know the database you use.

**Comment by sunnyxiaohu** [comment]
Thumos14, or any other action detection datasets.

**Comment by honest2017** [comment]
Thank you for your reply.

**Comment by dangao250** [comment]
请问你 detclasslist.txt 里面是什么

**Comment by dangao250** [comment]
> Thank you for your reply.

detclasslist.txt 请问你里面是什么

**Comment by sunnyxiaohu** [comment]
你把THUMOS14数据集下好就看到了------------------ 原始邮件 ------------------
发件人: "dangao250"<notifications@github.com>
发送时间: 2019年10月31日(星期四) 下午4:24
收件人: "sunnyxiaohu/R-C3D.pytorch"<R-C3D.pytorch@noreply.github.com>;
抄送: "wang shiguang"<515740295@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [sunnyxiaohu/R-C3D.pytorch] problem (#14)


 
Thank you for your reply.
  
detclasslist.txt 请问你里面是什么
 
&mdash;
