### ISSUE TITLE
How do you train your data

### ISSUE THREAD

**Issue by caijiahao** [sunnyxiaohu/R-C3D.pytorch#15]
Hello developer, have you used this algorithm to train your own data? How do you train your data?

**Comment by sunnyxiaohu** [comment]
Hello,
Thanks for your interest. You can follow the these steps for your own data:
1. preparing data, which you can find the generate_frames.py , generate_roidb_xx.py in process/thumos14
2. adjusting the configs to suit for your dataset. They are mainly list in the cfgs folder and trainval_net.py
3. train and test as the normal process
4. evaluate. Note that if you do not want to rewrite the evaluation code, you could just prepare the data format as activitynet and thumos14 dataset do.
