### ISSUE TITLE
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 4 and 3 in dimension 1 at /pytorch/aten/src/TH/generic/THTensorMath.c:3586

### ISSUE THREAD

**Issue by EscargotXJ** [sunnyxiaohu/R-C3D.pytorch#16]
when I set batch_size bigger than 1, it makes below mistake.
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 4 and 3 in dimension 1 at /pytorch/aten/src/TH/generic/THTensorMath.c:3586
How can I deal with it?

**Comment by sunnyxiaohu** [comment]
It's because the gt_wins of samples in a batch are not match. You can realize your own collate_fn in the dataloader or just use the MAX_NUM_GT_TWINS settings. I have fixed the bug in the new version.

**Comment by rambleramble** [comment]
I encountered the same issue, I didn't see the update of code.Could you provide the fix link @sunnyxiaohu ?  Thanks a lot!

**Comment by sunnyxiaohu** [comment]
@rambleramble Did you get the newest version ?

**Comment by rambleramble** [comment]
Yes, and it is only working for these following commands:
`python trainval_net.py --dataset thumos14 --net c3d --bs 2 --nw 4 --lr 0.0001 --lr_decay_step 3 --gpus 0 1
`
but not working if only change --bs 2 (others the same as bove)
`python trainval_net.py --dataset thumos14 --net c3d --bs 4 --nw 4 --lr 0.0001 --lr_decay_step 3  --gpus 0 1`
Also, not working for 3 gpus
`python trainval_net.py --dataset thumos14 --net c3d --bs 3 --nw 4 --lr 0.0001 --lr_decay_step 3 --gpus 0 1 2`
or 4 gpus
`python trainval_net.py --dataset thumos14 --net c3d --bs 4 --nw 4 --lr 0.0001 --lr_decay_step 3 --gpus 0 1 2 3`

It is definitely beneficial if you could share the rules of using --bs  Thanks again!

**Comment by sunnyxiaohu** [comment]
I update it with commit: e7f4ab576d0628a48a207ea7badb516c23de7502
