### ISSUE TITLE
Could you provide other pretrained weight "activitynet_iter_30000_3fps-caffe.pth,c3d_sports1M.pth"?

### ISSUE THREAD

**Issue by dongzhuoyao** [sunnyxiaohu/R-C3D.pytorch#17]

**Comment by sunnyxiaohu** [comment]
I have uploaded the pretrained model with link in the README.md

**Comment by akc5233206** [comment]
@sunnyxiaohu Hi thank you for your work. It seemed URLs to OneDrive in the README.md are not working anymore. Could you please provide new ones? I wish to have activitynet_iter_30000_3fps-caffe.pth to test the model training. 

Thank you for your time.

**Comment by sunnyxiaohu** [comment]
we updated the URLs, you can just refer to the newest repo.
