### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by Augus-smile** [sunnyxiaohu/R-C3D.pytorch#19]
Hello, in the stage of training, the program reported the following error:: 
/media/ext/xxx/UCF-101/annotation_val/ApplyEyeMakeup_val.txt
 
Is this file downloaded or not? Where should I download it? Thank you!

**Comment by rambleramble** [comment]
@Augus-smile 
you can find it here
https://github.com/sunnyxiaohu/R-C3D.pytorch/tree/master/evaluation/thumos14/Evaluation/annotation
