### ISSUE TITLE
How convert the pretrained caffemodels to pytorch?

### ISSUE THREAD

**Issue by guoswang** [sunnyxiaohu/R-C3D.pytorch#2]
Hi, 
Thanks for your great works.
Can you share the codes about converting the pretrained caffemodels to pytorch and  the links for "ucf101-caffe.pth" ?
Thanks a lot!

**Comment by sunnyxiaohu** [comment]
I updated the converted pretrained model in README. For more converting details, you can refer to https://github.com/sunnyxiaohu/pytorch-caffe-darknet-convert for help.

**Comment by AnubhaPandey** [comment]
Hi,

I am not able to download the pre-trained model "ucf101-caffe.pth" from the [link](https://pan.baidu.com/s/1saNqGBkzZHwZpG-A5RDLVw)  you have mentioned in the README . It seems Baidu account is required for downloading and I can't register because I don't have china's phone number.

Thanks

**Comment by sunnyxiaohu** [comment]
Hi, 
I also upload the pretrained model on OneDrive: https://1drv.ms/u/s!Asa9-hE0xR2KgRlSECoq_yv1BVtk

Thanks

**Comment by AnubhaPandey** [comment]
@sunnyxiaohu Thankyou so much!
