### ISSUE TITLE
any evaluation results with baselines？

### ISSUE THREAD

**Issue by rambleramble** [sunnyxiaohu/R-C3D.pytorch#21]
Can you comment on how the test results compare to Huijuan Xu's paper, Table 1 and 2 particularly？
https://arxiv.org/pdf/1703.07814.pdf

In terms of the testing performance, what would be the outcome of your test commands?
Particularly, if any results compare to Huijuan's results in this link below
https://github.com/VisionLearningGroup/R-C3D/tree/master/experiments/thumos14

Thanks a lot!

**Comment by rambleramble** [comment]
Also, it is much appreciated if you can provide an instruction on reproduction steps 
such that from the generated results.json (after thumos14_log_analysis.py)
https://github.com/sunnyxiaohu/R-C3D.pytorch/blob/master/evaluation/thumos14/results.json
to the record:
https://github.com/sunnyxiaohu/R-C3D.pytorch/blob/master/evaluation/thumos14/record

thank you!

**Comment by sunnyxiaohu** [comment]
I have updated it.
Thanks.
