### ISSUE TITLE
why USE_FLIPPED  = True ?

### ISSUE THREAD

**Issue by rambleramble** [sunnyxiaohu/R-C3D.pytorch#22]
In your code, during associatng training data, the flag USE_FLIPPED is set TRUE
https://github.com/sunnyxiaohu/R-C3D.pytorch/blob/master/preprocess/thumos14/generate_roidb_training.py#L130

It seems the counterpart in Huijuan Xu's code is set to False.
https://github.com/VisionLearningGroup/R-C3D/blob/master/preprocess/thumos14/test/generate_roidb_512_full.py#L16

Can you comment on why you set it to be True?
Thanks!

**Comment by sunnyxiaohu** [comment]
It dose not make any sense, you can just ignore it ~
Thanks
