### ISSUE TITLE
some question about the result?

### ISSUE THREAD

**Issue by hduwqw** [sunnyxiaohu/R-C3D.pytorch#27]
I read the  paper R-C3D,the original paper used C3D to extract the feature.I dont understand why there is an another  single C3D expriments?

**Comment by hduwqw** [comment]
my  e-mail is 442634234@qq.com.hope your reply!

**Comment by sunnyxiaohu** [comment]
It's our re-implementation

**Comment by hduwqw** [comment]
i got it ,thank you
