### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by Syrup274** [sunnyxiaohu/R-C3D.pytorch#3]
I encountered the following issue when running make.sh and I don't know what to do:
```

R-C3D.pytorch/lib/model/nms/src/nms_cuda.c:14:22: error: dereferencing pointer to incomplete type ‘THTensor {aka struct THTensor}’
            boxes_host->size[0], 
                      ^
Traceback (most recent call last):
  File "build.py", line 37, in <module>
    ffi.build()
  File "/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by sunnyxiaohu** [comment]
How about your compiling environment ?

**Comment by Syrup274** [comment]
this is the complete info, i think it includes my compiling environment info.
`
Compiling nms kernels by nvcc...
Including CUDA code.
/home/wangzhe/R-C3D.pytorch/lib/model/nms
['/home/wangzhe/R-C3D.pytorch/lib/model/nms/src/nms_cuda_kernel.cu.o']
generating /tmp/tmpXdM0ru/_nms.c
setting the current directory to '/tmp/tmpXdM0ru'
running build_ext
building '_nms' extension
creating home
creating home/wangzhe
creating home/wangzhe/R-C3D.pytorch
creating home/wangzhe/R-C3D.pytorch/lib
creating home/wangzhe/R-C3D.pytorch/lib/model
creating home/wangzhe/R-C3D.pytorch/lib/model/nms
creating home/wangzhe/R-C3D.pytorch/lib/model/nms/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DWITH_CUDA -I/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python2.7 -c _nms.c -o ./_nms.o -std=c99
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DWITH_CUDA -I/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include -I/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python2.7 -c /home/wangzhe/R-C3D.pytorch/lib/model/nms/src/nms_cuda.c -o ./home/wangzhe/R-C3D.pytorch/lib/model/nms/src/nms_cuda.o -std=c99
/home/wangzhe/R-C3D.pytorch/lib/model/nms/src/nms_cuda.c: In function ‘nms_cuda’:
/home/wangzhe/R-C3D.pytorch/lib/model/nms/src/nms_cuda.c:14:22: error: dereferencing pointer to incomplete type ‘THTensor {aka struct THTensor}’
            boxes_host->size[0], 
                      ^
Traceback (most recent call last):
  File "build.py", line 37, in <module>
    ffi.build()
  File "/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/wangzhe/py2_torch0.4.0/local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

my gcc version:
`Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.9' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 
`
nvcc version:
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
`

Thanks!

**Comment by sunnyxiaohu** [comment]
How about your GPU?

**Comment by Syrup274** [comment]
my GPU is GeForece 1080 Ti, Driver Version: 375.82

**Comment by Syrup274** [comment]
$LD_LIBRARY_PATH
/usr/local/cuda/lib64:

$PATH
/home/wangzhe/py2_torch0.4.0/bin:/home/wangzhe/bin:/home/wangzhe/.local/bin:/monchickey/ffmpeg/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

CUDA Version 8.0.61

**Comment by sunnyxiaohu** [comment]
Try pytorch-0.4 with python=3.x, it would be helpfull.

**Comment by LiChenyang-Github** [comment]
> $LD_LIBRARY_PATH
> /usr/local/cuda/lib64:
> 
> $PATH
> /home/wangzhe/py2_torch0.4.0/bin:/home/wangzhe/bin:/home/wangzhe/.local/bin:/monchickey/ffmpeg/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> 
> CUDA Version 8.0.61

hi,

I have met the same problems. How did you solve this problem finally? Thx.
