### ISSUE TITLE
How to set suitable anchor scales in different dataset?

### ISSUE THREAD

**Issue by guancheng817** [sunnyxiaohu/R-C3D.pytorch#34]
Thanks for your great works, i am new in activity detection, my questions is , how to set suitable anchor scales in different datasets. The anchor scales of Thumos you set is [2,4,5,6,8,9,10,12,14,16], and that of ActivityNet is [1,1.25, 1.5,1.75, 2,2.5, 3,3.5, 4,4.5, 5,5.5, 6,7, 8,9,10,11,12,14,16,18,20,22,24,28,32,36,40,44,52,60,68,76,84,92,100], how do you set that? What about Charades dataset, thanks for your replying.

**Comment by sunnyxiaohu** [comment]
You can refer to the original R-C3D paper.

**Comment by guancheng817** [comment]
> You can refer to the original R-C3D paper.

thanks..
