### ISSUE TITLE
关于代码的一些问题

### ISSUE THREAD

**Issue by justKLK** [sunnyxiaohu/R-C3D.pytorch#35]
冒昧的问下作者 这份代码可以用吗？

不知道是不是我下的代码版本有问题
首先编译文件里面就有问题
然后是test.net加载自己训练好的模型dict的keys是对不上的
分析日志的时候 确定end_time的时候也是有问题的 直接把right_frame置成end_time会导致result.json预测出来的结果右边时间小于左边的
我用代码跑的mAP最高只有0.006多。。

**Comment by sunnyxiaohu** [comment]
可以的
