### ISSUE TITLE
pytorch 1.0 version

### ISSUE THREAD

**Issue by guancheng817** [sunnyxiaohu/R-C3D.pytorch#36]
Hi,  thanks for your great works, this repo run successfully in pytroch 0.4. But it will occur errors when it run in pytorch 1.0  because the torch.utils.ffi is deprecated. So it will be great to  support pytorch 1.0, thanks for your works again ..

**Comment by sunnyxiaohu** [comment]
Hi, thanks for your interest. I will support it later.
