### ISSUE TITLE
Inference the model use my own video

### ISSUE THREAD

**Issue by dagongji10** [sunnyxiaohu/R-C3D.pytorch#37]
@sunnyxiaohu I want to use R-C3D.pytorch to get the performance. The dataset ThUMOS14 is too large, so I want to just use less untrimmed-video defined by myself to test the model.
Is it realistic? How can I realize it?

**Comment by Maruidear** [comment]
Have you solved the problem?

**Comment by dagongji10** [comment]
> Have you solved the problem?

No， I use TSN instead of R-C3D to do action_recognize.

**Comment by Maruidear** [comment]
> > 你解决了这个问题吗？
> 
> 不，我用TSN代替R-C3D进行action_recognize。

Have you successfully converted your own data set with TSN?

**Comment by dagongji10** [comment]
> > > 你解决了这个问题吗？
> > 
> > 
> > 不，我用TSN代替R-C3D进行action_recognize。
> 
> Have you successfully converted your own data set with TSN?

Yeah, I use TSN to extract 1024-dim action feature, it seems work.

**Comment by Maruidear** [comment]
> > > > 你解决了这个问题吗？
> > > 
> > > 
> > > 不，我用TSN代替R-C3D进行action_recognize。
> > 
> > 
> > 您是否已使用TSN成功转换了自己的数据集？
> 
> 是的，我使用TSN提取1024-dim动作功能，看来可行。

Thank you very  much for your reply.
