### ISSUE TITLE
training and inference are slow

### ISSUE THREAD

**Issue by coolbay** [sunnyxiaohu/R-C3D.pytorch#40]
I am trying training and inferencing the model on my 1080TI GPU. But it takes too much time. Running one epoch takes almost a day, which is far slower than the reported time. I directly use the provided Pytorch code. Do you have any clue why is this? 

Thank you very much!

**Comment by sunnyxiaohu** [comment]
Did you use solid state disk?

**Comment by coolbay** [comment]
No. I am running on a rotational disk.

**Comment by sunnyxiaohu** [comment]
a solid state disk would get a smoothly training.
