### ISSUE TITLE
pytorch1.1 no dist_utils

### ISSUE THREAD

**Issue by WXYsunshy** [sunnyxiaohu/R-C3D.pytorch#51]
Traceback (most recent call last):
  File "./trainval_net.py", line 25, in <module>
    from model.utils.dist_utils import dist_init, average_gradients, DistModule, get_world_size
ModuleNotFoundError: No module named 'model.utils.dist_utils'

**Comment by qinguoyi** [comment]
hi, do you solve this question?

**Comment by yukeqi12345** [comment]
no

**Comment by sunnyxiaohu** [comment]
Hi,
Comment this line would solve this issue temporatelly.
