### ISSUE TITLE
pytorch1.1 dont have dist model

### ISSUE THREAD

**Issue by yukeqi12345** [sunnyxiaohu/R-C3D.pytorch#54]
![image](https://user-images.githubusercontent.com/36193935/69771745-d3a29380-11c8-11ea-8d99-61f9d93b7159.png)
![image](https://user-images.githubusercontent.com/36193935/69771749-d7361a80-11c8-11ea-9fbb-edd66894fc60.png)

**Comment by qinguoyi** [comment]
do you solve this queation?

**Comment by qinguoyi** [comment]
do you solve this question?

**Comment by yukeqi12345** [comment]
no ,the author don't give us

**Comment by qinguoyi** [comment]
do you try to train with discard this code

**Comment by yukeqi12345** [comment]
no，the author don't give us the py
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "qinguoyi"<notifications@github.com&gt;; 
发送时间: 2019年12月5日(星期四) 上午10:48
收件人: "sunnyxiaohu/R-C3D.pytorch"<R-C3D.pytorch@noreply.github.com&gt;; 
抄送: "1144581929"<1144581929@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [sunnyxiaohu/R-C3D.pytorch] pytorch1.1 dont have dist model (#54)




do you solve this queation?

**Comment by qinguoyi** [comment]
hi, i discard this code with "#", and i run this code successfully.

**Comment by yukeqi12345** [comment]
what is your GPU，and my GPU is a  2080TI 。 I run the code in pytorch0.4 and my computer reboot

**Comment by qinguoyi** [comment]
i run the code successfully on both server with GPU 2080TI & Pytorch1.0 and my private computer with GPU 1070 & Pytorch 0.4.0.

**Comment by qinguoyi** [comment]
i run the code successfully on both server with GPU 2080TI & Pytorch1.1.0 and my private computer with GPU 1070 & Pytorch 0.4.0.

**Comment by yukeqi12345** [comment]
what is your setting ？my bs is 1，nw is 2 learning date is 0.001，and the GPU-Util is 97％，i am a little unhappy and i think maybe my computer will reboot

**Comment by qinguoyi** [comment]
> what is your setting ？my bs is 1，nw is 2 learning date is 0.001，and the GPU-Util is 97％，i am a little unhappy and i think maybe my computer will reboot

I did not change any parameters. 

After training and testing the day before yesterday, I found that when tIOU = 0.5, mAP = 39.55%, which is about 2 percentage points higher than the open source.

I think it may be a platform bonus
