### ISSUE TITLE
the code of pytorch1.1 branch is the MSCA-Net or R-C3D.pytorch baseline

### ISSUE THREAD

**Issue by qinguoyi** [sunnyxiaohu/R-C3D.pytorch#59]
as the title. 

the code of pytorch1.1 branch is the MSCA-Net or R-C3D.pytorch baseline?

thank you.

**Comment by sunnyxiaohu** [comment]
pytorch1.1 branch is the pytorch1.1 implementation of R-C3D.pytorch。
