### ISSUE TITLE
Some question about data?

### ISSUE THREAD

**Issue by lawliet1718** [sunnyxiaohu/R-C3D.pytorch#6]
Excuse me.Could you give me a website to download the Thumas-14 data?I have tried to use the UCF-101 data to run but it didn't work.So thank you.

**Comment by sunnyxiaohu** [comment]
http://crcv.ucf.edu/THUMOS14/download.html
Thanks

**Comment by lawliet1718** [comment]
First at all, thanks  for  your answer.But I want to know the way to download the data for Temporal annotations of actions ,while it is so large to download all the untrimmed videos data.Sorry for my description ago.

**Comment by sunnyxiaohu** [comment]
As far as I know, you have to download all the untrimmed videos data firstly, and then select the these temporal labeled videos using the temporal annotations of actions (http://crcv.ucf.edu/THUMOS14/Validation_set/TH14_Temporal_annotations_validation.zip).

**Comment by lawliet1718** [comment]
All right,it is really a tricky problem for me without Wi-fi nearby.Thanks you.

**Comment by lawliet1718** [comment]
All right , I will try to solve it. Thank you very much.
