### ISSUE TITLE
question about generate_frame

### ISSUE THREAD

**Issue by wade12138** [sunnyxiaohu/R-C3D.pytorch#9]
excuse me, i have already download the videos and annotation. When i try to run generate_frame.py, i got an error:
![default](https://user-images.githubusercontent.com/38905006/46950285-d1f63900-d0b6-11e8-95e6-4d3f58d15e56.png)
Is there anything i should change or could you explain the meaning of this function
![default](https://user-images.githubusercontent.com/38905006/46950426-4204bf00-d0b7-11e8-95d7-428d24c78ae8.png)
thanks a lot!

**Comment by sunnyxiaohu** [comment]
you have to install ffmpeg first.

**Comment by dangao250** [comment]
> excuse me, i have already download the videos and annotation. When i try to run generate_frame.py, i got an error:
> ![default](https://user-images.githubusercontent.com/38905006/46950285-d1f63900-d0b6-11e8-95e6-4d3f58d15e56.png)
> Is there anything i should change or could you explain the meaning of this function
> ![default](https://user-images.githubusercontent.com/38905006/46950426-4204bf00-d0b7-11e8-95d7-428d24c78ae8.png)
> thanks a lot!

请问您怎么解决这个问题的  我现在 输出是空的文件夹 没有剪切出视频帧

**Comment by Maruidear** [comment]
> > 对不起，我已经下载了视频和注释。当我尝试运行generate_frame.py时，出现一个错误：
> > 有什么我应该更改的吗？或者您能解释一下此函数的含义，
> > 非常感谢！
> > ![默认](https://user-images.githubusercontent.com/38905006/46950285-d1f63900-d0b6-11e8-95e6-4d3f58d15e56.png)
> > ![默认](https://user-images.githubusercontent.com/38905006/46950426-4204bf00-d0b7-11e8-95d7-428d24c78ae8.png)
> 
> 请问您怎么解决这个问题的我现在输出是空的文件夹没有剪切出视频帧

Hi.Have you solved the problem? What I output now is also an empty folder.
